spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:challenging
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true
  redis:
    host: localhost
    port: 6379

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /index.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    doc-expansion: none           # 접어둔 상태
  api-docs:
    path: /api-docs
  cache:
    disabled: true
