spring:
  on-profiles:
    active: local

server:
  servlet:
    context-path: /api

logging:
  level:
    b172.challenging: debug

jwt:
  secret: "sdaspdjaskdjsaknfoasofnqwownfqfjoqwfnouwqnvownquvnqiwunvqviwqnowvniqwvuqwnivnqiwnvuiqwnviqwnvqwuinvuqiwnvwqiuvwnwuqivquiwdxn"
  expiration: 3600000

---
spring:
  on-profiles: local
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  sql:
    init:
      enabled: true

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /index.html
    #disable-swagger-default-url: true
    #display-query-params-without-oauth2: true
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true